app/connectors/ApplicationClient.scala, app/controllers/ActivationController.scala, app/controllers/ApplicationController.scala, app/controllers/AssistanceController.scala, app/controllers/BaseController.scala, app/controllers/FastStreamApplication.scala, app/controllers/HomeController.scala, app/controllers/LockAccountController.scala, app/controllers/OnlineTestController.scala, app/controllers/PasswordResetController.scala, app/controllers/QuestionnaireController.scala, app/controllers/ReviewApplicationController.scala, app/controllers/SchemeController.scala, app/controllers/SignInController.scala, app/controllers/SignUpController.scala, app/controllers/SubmitApplicationController.scala, app/security/SignInService.scala, app/views/application/assistance.scala.html, app/views/govuk_template.scala.html, app/views/home/dashboard.scala.html, app/views/questionnaire/continue.scala.html, app/views/questionnaire/index.scala.html, app/views/registration/signup.scala.html, app/views/widgets/onlineTestProgress.scala.html, conf/app.routes, test/controllers/LandingPageControllerSpec.scala
Controllers have been refactored to follow the style of other CSR projects.
We pass ApplicationClient as a dependency but we still mix-in SignInService.
=> Controllers have been refactored to follow the style of other CSR projects.

app/config/frontendAppConfig.scala, app/config/frontendWiring.scala, conf/application.conf, project/MicroService.scala, test/util/RegionToJsonSpec.scala
A mirror of this change: https://github.com/hmrc/fset-fasttrack-frontend/pull/3/files
=> A mirror of a fasttrack change that removes the old/outdated notion of Dev/Test/Prod from our config

app/connectors/UserManagementClient.scala, app/security/CsrCredentialsProvider.scala, test/security/CsrCredentialsProviderSpec.scala
Add unit test to CsrCredentialsProvider
=> Fset 585 - Lock a candidate's account

project/plugins.sbt
@henricook can you take a quick look?
=> Update sbt-auto-build plugin to latest version to test whether it builds

app/mappings/Address.scala
This limit is required by some of the 3rd party services which we are integrating with
=> FSET-739: Update address line1-4 max length to 100

app/views/index/locked.scala.html
=> FSET-740 Lock a candidate's account message should display the text number not amount

app/views/application/previewapplication/schemePreferencesViewSection.scala.html, conf/messages
scheme text where joined together
=> Fset 758: fix for bug on preview page

app/connectors/ApplicationClient.scala, app/connectors/exchange/package.scala, app/controllers/SignUpController.scala, app/forms/SignUpForm.scala, app/models/CampaignReferrers.scala, app/views/registration/signup.scala.html, test/controllers/forms/SignUpFormSpec.scala
Also added a bit of refactoring and change "media" for the less misleading "referrer"
=> FSET-634: Added marketing info

app/models/view/questionnaire/Universities.scala
=> Bug Fix in FSET-596 - Change the value of other universities option in education questionnaire

app/forms/EducationQuestionnaireForm.scala, test/controllers/forms/EducationQuestionnaireFormExamples.scala, test/controllers/forms/EducationQuestionnaireFormSpec.scala
There was a bug when saving education questionnaire after some other changes. Now it should save university-degree questions.
Original story was FSET-596
https://jira.tools.tax.service.gov.uk/browse/FSET-596
This is a one project review.
Acceptance tests passed
=> Bug fix saving education questionnaire

app/connectors/SchoolsClient.scala, app/connectors/exchange/School.scala, app/controllers/SchoolsController.scala, app/views/govuk_template.scala.html, app/views/questionnaire/secondpage.scala.html, conf/app.routes, public/js/scripts.js
=> Fset 782 - School List 

app/connectors/exchange/CivilServiceExperienceDetails.scala, app/connectors/exchange/CivilServiceExperienceDetailsExamples.scala, app/connectors/exchange/package.scala, app/controllers/PersonalDetailsController.scala, app/controllers/PreviewApplicationController.scala, app/controllers/QuestionnaireController.scala, app/controllers/SchemePreferencesController.scala, app/forms/FastPassForm.scala, app/forms/GeneralDetailsForm.scala, app/models/ApplicationData.scala, app/security/Roles.scala, app/views/application/civilServiceExperienceDetails/civilServantsContent.scala.html, app/views/application/civilServiceExperienceDetails/civilServiceExperienceDetailsPanel.scala.html, app/views/application/civilServiceExperienceDetails/civilServiceExperienceTypesPanel.scala.html, app/views/application/civilServiceExperienceDetails/fastPassCertificatePanel.scala.html, app/views/application/civilServiceExperienceDetails/fastTrackContent.scala.html, app/views/application/civilServiceExperienceDetails/internshipTypesPanel.scala.html, app/views/application/generalDetails.scala.html, app/views/application/previewapplication/generalDetailsViewSection.scala.html, conf/messages, test/connectors/exchange/GeneralDetailsExamples.scala, test/controllers/GeneralDetailsToExchangeConverterSpec.scala, test/controllers/PersonalDetailsControllerSpec.scala, test/controllers/SchemePreferencesControllerSpec.scala, test/controllers/forms/FastPassFormSpec.scala, test/controllers/forms/GeneralDetailsFormExamples.scala, test/models/CachedDataExample.scala
https://github.com/hmrc/fset-faststream/pull/71
https://github.tools.tax.service.gov.uk/HMRC/fset-faststream-candidate-acceptance-tests/pull/41
=> FSET-808: Rename fastpass-details to civil-service-experience-details and fastPassType to civilServiceExperienceType

app/forms/EducationQuestionnaireForm.scala, app/views/questionnaire/components/universityName.scala.html
University name control was not cleared when we choose prefer not to say checkbox.
https://jira.tools.tax.service.gov.uk/browse/FSET-816
=> FSET 816 - Education - What is the name of the university you received your degree from? text box is not hidden

app/views/questionnaire/components/postcode.scala.html, app/views/questionnaire/components/school.scala.html, app/views/questionnaire/components/universityDegreeCategory.scala.html, app/views/questionnaire/components/universityName.scala.html, app/views/widgets/selectValueDifferentFromDisplayedText.scala.html, public/js/scripts.js
FSET-816 Bug fix: Education - What is the name of the university you received your degree from? text box is not hidden
Please review it carefully as there are some javascript changes and that is not my speciallity.
Please suggest if there is a better way to do it, writing less code
=> FSET-816 Bug fix: Education - What is the name of the university you received your degree from? text box is not hidden

app/security/Roles.scala, app/views/widgets/onlineTestProgress.scala.html
This should be merged along with https://github.com/hmrc/fset-faststream/pull/128
=> FSET-687: Added e-try expiry message to the dashboard

app/connectors/ApplicationClient.scala, app/controllers/LaunchpadTestController.scala, app/views/application/onlineTests/phase3TestsComplete.scala.html, app/views/widgets/onlineTestProgress.scala.html, conf/app.routes
Depends on: https://github.com/hmrc/fset-faststream/pull/173, which is blocked by preceding PRs
=> FSET-692: Mark Video Interview (VI) as started and complete, new dashboard text, landing page for VI completion

app/connectors/ApplicationClient.scala, app/controllers/HomeController.scala, app/models/Adjustments.scala, app/models/page/DashboardPage.scala, app/models/page/Phase3TestsPage.scala, app/views/home/dashboard.scala.html, app/views/widgets/onlineTestProgress.scala.html, test/models/page/DashboardPageSpec.scala
Also: Remove all legacy references to assessments/'allocationDetails'
=> FSET 691: Show users who will be e-tray invigilated a "we'll get in touch" message

app/connectors/ApplicationClient.scala, app/controllers/InvigilatedController.scala, conf/messages, test/controllers/InvigilatedControllerSpec.scala
Added logic to take case of an expired phase 2 test for invigilated e-tray.
Also added unit test for the controller.
=> Fset 814 test

app/config/frontendAppConfig.scala, app/controllers/BaseController.scala, app/controllers/CampaignAwareController.scala, app/controllers/HomeController.scala, app/controllers/SignUpController.scala, app/controllers/SubmitApplicationController.scala, app/views/registration/chooseYourRoute.scala.html, app/views/registration/signup.scala.html, test/controllers/ApplicationRouteConfigSpec.scala, test/controllers/HomeControllerSpec.scala, test/controllers/SignUpControllerSpec.scala, test/controllers/SubmitApplicationControllerSpec.scala, test/testkit/BaseControllerSpec.scala
@satishkamatam see what you think about this refactoring. More importantly, does it work ;-)
=> Faststream timeszone fix refactor

app/views/registration/chooseYourRoute.scala.html
Prototype for reference: https://faststream-prototype.herokuapp.com/faststream/profile-create.html
=> Add 'or disabled' to sdip eligibility text

app/controllers/ConsiderForSdipController.scala, app/models/ConsiderMeForSdipHelper.scala, app/views/home/dashboard.scala.html, app/views/registration/signup.scala.html, test/controllers/ConsiderForSdipControllerSpec.scala, test/controllers/SignUpControllerSpec.scala
Changes to prevent faststream users converting to SDIP after the SDIP window has closed
=> FSET-982 Stop faststream users converting to SDIP after window has closed

app/connectors/ApplicationClient.scala, app/connectors/UserManagementClient.scala, app/connectors/exchange/AddReferral.scala, app/connectors/exchange/ApplicationResponse.scala, app/connectors/exchange/EmailWrapper.scala, app/connectors/exchange/InvigilatedTestUrl.scala, app/connectors/exchange/PersonalDetails.scala, app/connectors/exchange/PersonalDetailsAdded.scala, app/connectors/exchange/RegistrationEmail.scala, app/connectors/exchange/Requests.scala, app/connectors/exchange/UpdateDetails.scala, app/connectors/exchange/UserResponse.scala, app/controllers/SignUpController.scala, app/security/CsrCredentialsProvider.scala, app/security/UserCacheService.scala
=> Move case classes out of exchange package object to remove compiler

app/views/registration/signup.scala.html, test/controllers/SignUpControllerSpec.scala
Disable sign up page functionality if faststream, edip and sdip account creation is blocked
=> FSET-1057 Handle account creation being blocked for FS, EDIP and SDIP

app/connectors/exchange/ProgressResponse.scala, app/models/Progress.scala, app/security/Roles.scala, app/views/home/dashboard.scala.html, app/views/widgets/sdipFaststreamBanner.scala.html, test/connectors/exchange/ProgressExamples.scala, test/models/ProgressResponseExamples.scala
Needs https://github.com/hmrc/fset-faststream/pull/303 to be merged first!
=> FSET-1056: Notify SDIP-Fast Stream candidates for failed test

.gitignore, app/models/page/DurationFormatter.scala, app/models/page/Phase1TestsPage.scala, app/models/page/Phase2TestsPage.scala, app/models/page/Phase3TestsPage.scala, app/views/widgets/onlineTestProgress.scala.html, test/models/page/DurationFormatterSpec.scala
Shift the date formatter code to the DateFormatter trait.
=> FSET-1485 Add in the expiry date for the various tests to the candidate dashboard.

app/connectors/exchange/UserResponse.scala, test/connectors/UserManagementClientSpec.scala, test/controllers/ConsiderForSdipControllerSpec.scala, test/security/CsrCredentialsProviderSpec.scala, test/security/UserCacheServiceSpec.scala
There are 6 PRs for this jira ticket:
-https://github.com/hmrc/fset-faststream/pull/338
https://github.com/hmrc/fset-faststream-frontend/pull/197
-fset-faststream-admin-frontend
-fset-faststream-admin-acceptance-tests
-csr-auth-provider
-fset-email-renderer
=> [fset-1499] Manage existing admin user (edit/deactivate)

app/config/frontendAppConfig.scala, app/connectors/UserManagementClient.scala, app/connectors/exchange/UserResponse.scala, conf/application.conf
FSET-1501 and FSET-1499 bug 1 are related and should be merged together
4 PRs:
https://github.com/hmrc/fset-faststream/pull/340
https://github.com/hmrc/fset-faststream-frontend/pull/198
and front end admin faststream (2 PRs one for fset-1499-bug1 and the other for fset-1501
=> [Fset-1501] End session for deactivating Admin users

public/js/addressLookup.js
=> Hide the "x addresses found" message if another search is made that is

app/connectors/exchange/School.scala, app/models/view/SchoolView.scala, app/views/application/previewapplication/personalDetailsViewSection.scala.html
2 PRs:
-One in faststream candidate acceptance tests
-This one: https://github.com/hmrc/fset-faststream-frontend/pull/201
=> Fix for Failing FastStream Candidate Acceptante Tests

app/config/frontendWiring.scala
port over fix from Fast Track to make session authenticator check the client identity case insensitively to fix post code lookup in IE9.
=> FSET-1548 Post Code lookup IE9 fix

project/build.properties, public/js/schemeSelection.js
re-selected when revisitng the page. Tidy up unused variables.
Bump sbt to latest version.
=> FSET-1605 Correct variable name in schemeSelection.js so that schemes are

app/controllers/HomeController.scala, app/controllers/SiftQuestionsController.scala, app/helpers/CachedUserMetadata.scala, app/helpers/CachedUserWithSchemeData.scala, app/models/page/PostOnlineTestsPage.scala, app/security/SecureActions.scala, app/security/SignInService.scala, app/views/application/additionalquestions/generalQuestions.scala.html, app/views/application/additionalquestions/previewAdditionalAnswers.scala.html, app/views/home/postOnlineTestsDashboard.scala.html, app/views/home/siftProgress.scala.html, test/controllers/HomeControllerSpec.scala, test/models/page/PostOnlineTestsPageSpec.scala, test/security/SecureActionsSpec.scala
Fixed dashboard doesn't refresh, add missing answers to sift preview and don't display labels for blank answers
=> Fset 1634 - Fixes to dashboard status and sift preview

app/views/home/postOnlineTestsDashboard.scala.html, app/views/home/siftProgress.scala.html
From an missed set of renames during an intellij refactor (resolves branch fset-1634 merge a few moments ago)
=> FSET-1634 - Resolve intellij refactor build break

app/views/application/civilServiceExperienceDetails/civilServiceExperienceDetailsPanel.scala.html, app/views/application/civilServiceExperienceDetails/fastPassCertificatePanel.scala.html, app/views/home/dashboard.scala.html, app/views/index/signin.scala.html, app/views/registration/chooseYourRoute.scala.html, app/views/registration/signup.scala.html, app/views/widgets/onlineTestProgress.scala.html, conf/messages
As I've realised one big PR is probably not a good idea with this, I'm splitting it up into more manageable, mergeable PR's by cherry-picking from the previous branch I was working on.
=> Partial content changes for Fast Stream candidate

app/views/registration/signup.scala.html
We don't need this now as site is not visible internally
=> Remove notice on create account page

app/views/application/additionalquestions/generalQuestions.scala.html, app/views/application/additionalquestions/previewAdditionalAnswers.scala.html, app/views/application/additionalquestions/schemespecific.scala.html, app/views/home/postOnlineTestsDashboard.scala.html, app/views/home/schemeWithdraw.scala.html, app/views/home/siftProgress.scala.html
* Tweaks to text on nationality and education pages
* Correct class for withdrawal reason
* Minor changes to dashboard view
=> Content changes post video interview

app/views/application/assistancedetails/hasDisability.scala.html, app/views/application/assistancedetails/needsSupportAtVenue.scala.html, app/views/application/assistancedetails/needsSupportOnlineAssessments.scala.html, app/views/application/previewapplication/assistanceDetailsViewSection.scala.html, app/views/home/dashboard.scala.html, app/views/home/siftProgress.scala.html, conf/messages, test/controllers/AssistanceDetailsControllerSpec.scala, test/controllers/PreviewApplicationControllerSpec.scala
There seems to be a bug with extra support being pulled into the preview page. However these changes are just to update the labels and hints
=> FSET-1440: Updated text for disability and health conditions page and preview

app/controllers/HomeController.scala, conf/messages
Logging is temporarily WARN so it's clearly visible in production while we debug
=> FSET-1847: Add a minimum file size, and logging to track the size of uploaded files

app/connectors/ApplicationClient.scala, app/connectors/exchange/referencedata/Scheme.scala, app/controllers/HomeController.scala, app/controllers/SiftQuestionsController.scala, app/helpers/CachedUserWithSchemeData.scala, app/models/page/PostOnlineTestsPage.scala, app/views/home/postOnlineTestsDashboard.scala.html, test/controllers/HomeControllerSpec.scala, test/helpers/CachedUserWithSchemeDataSpec.scala, test/models/page/PostOnlineTestsPageSpec.scala
Labelled as Do Not Merge while I add tests for this functionality
=> FSET 1862: Update candidate dashboard messaging for "You are through for 0 of your preferred schemes"

app/security/Roles.scala
Reverts hmrc/fset-faststream-frontend#331
=> Revert "NOJIRA: extra logging to troubleshoot prod issue"

app/views/home/postOnlineTestsDashboard.scala.html, app/views/widgets/onlineTestProgress.scala.html, test/controllers/HomeControllerSpec.scala
4 PRs:
https://github.com/hmrc/fset-faststream-candidate-acceptance-tests/pull/15
https://github.com/hmrc/fset-faststream-admin-acceptance-tests/pull/21
https://github.com/hmrc/fset-faststream/pull/928
https://github.com/hmrc/fset-faststream-frontend/pull/358
=> Fset 2310 phase2 acceptance tests

app/views/registration/signup.scala.html
=> Fix duplicate ID issue

app/views/application/assistancedetails/hasDisability.scala.html, app/views/application/civilServiceExperienceDetails/civilServantsContent.scala.html, app/views/application/civilServiceExperienceDetails/fastPassCertificatePanel.scala.html, app/views/application/civilServiceExperienceDetails/fastTrackContent.scala.html, app/views/questionnaire/components/school.scala.html, app/views/registration/chooseYourRoute.scala.html
=> Accessibility p50 p51 p52

app/views/home/postOnlineTestsDashboard.scala.html, app/views/widgets/onlineTestProgress.scala.html, conf/messages, test/controllers/HomeControllerSpec.scala
https://jira.tools.tax.service.gov.uk/browse/FSET-2990
=> fset-2990: reenabling numerical test report link in dashboard

app/views/application/civilServiceExperienceDetails/civilServantsContent.scala.html, app/views/home/dashboard.scala.html, app/views/registration/chooseYourRoute.scala.html, app/views/widgets/onlineTestProgress.scala.html
https://jira.tools.tax.service.gov.uk/browse/FSET-2992
=> fset-2992: change /faqs/ to /faq/index.html

conf/application.conf
https://jira.tools.tax.service.gov.uk/browse/FSET-2894
=> fset-2894: removed play secret override

build.sbt, conf/application.conf, project/plugins.sbt
https://jira.tools.tax.service.gov.uk/browse/FSET-3001
=> fset-3001: PR boot comments addressed

conf/application.conf
Reverts hmrc/fset-faststream-frontend#558
=> Revert "FSET-3156 updated the fsac guide url"
